name: Run Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Add this line for access to the GitHub OIDC token
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true  # Enable publishing results to generate badge

      - name: Create Badge
        run: |
          # Create the badge markdown file
          echo "![Scorecard](https://img.shields.io/github/workflow/status/${{ github.repository }}?label=scorecard)" > badge.md

      - name: Commit Badge
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Add Scorecard badge"
          file_pattern: "badge.md"
